
services:
  # db_init:
  #   # build: .
  #   image: postgres
  #   volumes:
  #     - entrypoint:/docker-entrypoint-initdb.d
  db:
    build: .
    # image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dwh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-DBTTEST}
      POSTGRES_DB: ${POSTGRES_DB:-dwh}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - entrypoint:/docker-entrypoint-initdb.d
      # - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwh"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    # depends_on:
      # db_init:
      #   condition: service_completed_successfully
  
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://dwh:DBTTEST@db:5432/dwh}
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
    restart: on-failure:5
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /


volumes:
#   postgres-db-volume:
  entrypoint:
  PGDATA:
  