import psycopg2

conn = psycopg2.connect("postgresql://dwh:DBTTEST@localhost:5432/dwh")
conn.autocommit = True
cur = conn.cursor()

cur.execute('''
CREATE TABLE IF NOT EXISTS "RACINGAPP"."SERIESCONTROL"
(
    key     bigint NOT NULL PRIMARY KEY,
    year    varchar(255) NULL,
    name    varchar(255) NOT NULL,
    club    varchar(255) NULL
)
''')

cur.execute('''
ALTER TABLE "RACINGAPP"."SERIESCONTROL"
    ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY
''')

cur.execute('SELECT COUNT(*) FROM "RACINGAPP"."SERIESCONTROL"')
count = cur.fetchone()[0]
if count == 0:
    cur.execute('''
    INSERT INTO "RACINGAPP"."SERIESCONTROL" (key, year, name, club)
    VALUES (nextval('key'), '2026', 'Test Series', '1')
    ''')
    print('Inserted test series row')
else:
    print(f'SERIESCONTROL already has {count} rows')

print('SERIESCONTROL ready')
cur.close()
conn.close()
