CREATE SCHEMA "RACINGAPP";
CREATE SCHEMA "AUDIT";
CREATE SEQUENCE key START 1;


-- CREATE TABLE "RACINGAPP"."RACES"
-- (
-- 	key				bigint NOT NULL,
-- 	boat			varchar(255) NOT NULL,
-- 	sail_number		varchar(255) NOT NULL,
-- 	handicap 		int NULL,
-- 	club			bitint) NULL,
-- 	series			varchar(255) NULL,
-- 	race 			int NULL,
-- 	recorded_time 	timestamp NULL,
-- 	corrected_time 	timestamp NULL,
-- 	final_position 	int NULL
-- );

CREATE TABLE "RACINGAPP"."SERIESCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	year			varchar(255) NULL,
	name			varchar(255) NOT NULL,
	club			varchar(255) NULL
);

CREATE TABLE "RACINGAPP"."CLUBCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	name			varchar(255) NOT NULL
);

CREATE TABLE "RACINGAPP"."SAILORCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	FullName		varchar(255) NOT NULL,
	FirstName 		varchar(255) NOT NULL,
	LastName		varchar(255) NULL,
	club			bigint
);

CREATE TABLE "RACINGAPP"."HANDICAPCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	date			DATE NOT NULL,
	boat			varchar(255) NOT NULL,
	handicap		int NOT NULL
);

CREATE TABLE "RACINGAPP"."BOATCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	boat			bigint NOT NULL,
	sailor			bigint NOT NULL,
	sail_number		varchar(255) NOT NULL
);

CREATE TABLE "RACINGAPP"."RACEMASTER"
(
	key				bigint NOT NULL PRIMARY KEY,
	boatkey			bigint,
	club			bigint,
	series			bigint,
	race 			int NULL,
	recorded_time 	time NULL,
	corrected_time 	time NULL,
	time			time
);

CREATE TABLE "AUDIT".cdc
(
	TableName varchar(255) NULL,
	DateColumn varchar(255) NULL,
	LastLoadTimestamp date NULL
);


CREATE TEMPORARY TABLE temp_dest (boat varchar(255), handicap int);

COPY temp_dest(boat, handicap) FROM '/var/handicaps.csv' DELIMITER ',' csv header;

INSERT INTO "RACINGAPP"."HANDICAPCONTROL"
SELECT nextval('key'), current_timestamp, boat, handicap
FROM temp_dest;

ALTER TABLE "RACINGAPP"."RACEMASTER"
  ALTER COLUMN key SET DEFAULT nextval('key');


ALTER TABLE "RACINGAPP"."CLUBCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Series Control

-- ALTER TABLE "RACINGAPP"."SERIESCONTROL"
-- 	ALTER COLUMN year SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);

	
ALTER TABLE "RACINGAPP"."SERIESCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."SAILORCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."BOATCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;




-- ALTER TABLE "RACINGAPP"."SERIESCONTROL"
--   ADD CONSTRAINT seriescontrol_year_name_uq UNIQUE (y



