CREATE SCHEMA "RACINGAPP";
CREATE SEQUENCE key START 1;
CREATE EXTENSION IF NOT EXISTS pgcrypto;


CREATE TABLE "RACINGAPP"."SERIESCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	year			varchar(255) NULL,
	name			varchar(255) NOT NULL,
	club			varchar(255) NULL
);

CREATE TABLE "RACINGAPP"."CLUBCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	name			varchar(255) NOT NULL
);

CREATE TABLE "RACINGAPP"."CLUBUSER"
(
	key				bigint NOT NULL PRIMARY KEY,
	club			bigint NOT NULL REFERENCES "RACINGAPP"."CLUBCONTROL"(key),
	username		varchar(100) NOT NULL UNIQUE,
	password_hash		varchar(255) NOT NULL,
	is_active		boolean NOT NULL DEFAULT TRUE,
	created_at		timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_login		timestamp NULL
);

CREATE TABLE "RACINGAPP"."SAILORUSER"
(
	key				bigint NOT NULL PRIMARY KEY,
	sailor			bigint NOT NULL,
	username		varchar(100) NOT NULL UNIQUE,
	password_hash		varchar(255) NOT NULL,
	is_active		boolean NOT NULL DEFAULT TRUE,
	created_at		timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_login		timestamp NULL
);

CREATE TABLE "RACINGAPP"."SAILORCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	FullName		varchar(255) NOT NULL,
	FirstName 		varchar(255) NOT NULL,
	LastName		varchar(255) NULL,
	club			bigint
);

CREATE TABLE "RACINGAPP"."HANDICAPCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	date			DATE NOT NULL,
	boat			varchar(255) NOT NULL,
	handicap		int NOT NULL
);

CREATE TABLE "RACINGAPP"."BOATCONTROL"
(
	key				bigint NOT NULL PRIMARY KEY,
	boat			bigint NOT NULL,
	sailor			bigint NOT NULL,
	sail_number		varchar(255) NOT NULL
);

CREATE TABLE "RACINGAPP"."RACE"
(
	key				bigint NOT NULL PRIMARY KEY,
	club			bigint NOT NULL,
	series			bigint NOT NULL,
	race_no			int NOT NULL,
	status			varchar(50) NOT NULL DEFAULT 'not_started',
	started_at		timestamp NULL,
	ended_at		timestamp NULL
);

CREATE TABLE "RACINGAPP"."RACE_ENTRY"
(
	key				bigint NOT NULL PRIMARY KEY,
	race_id			bigint NOT NULL REFERENCES "RACINGAPP"."RACE"(key),
	boatkey			bigint NOT NULL,
	sailor			varchar(255) NOT NULL,
	boat			varchar(255) NOT NULL,
	sail_number		varchar(255) NOT NULL,
	handicap		int NULL
);

CREATE TABLE "RACINGAPP"."LAP"
(
	key				bigint NOT NULL PRIMARY KEY,
	race_entry_id		bigint NOT NULL REFERENCES "RACINGAPP"."RACE_ENTRY"(key),
	lap_number		int NOT NULL,
	is_finish		boolean NOT NULL DEFAULT FALSE,
	elapsed_sec		int NOT NULL,
	corrected_sec		int NULL,
	position		int NULL,
	recorded_at		timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT lap_unique_entry_number_finish UNIQUE (race_entry_id, lap_number, is_finish)
);

CREATE TEMPORARY TABLE temp_dest (boat varchar(255), handicap int);

COPY temp_dest(boat, handicap) FROM '/var/handicaps.csv' DELIMITER ',' csv header;

INSERT INTO "RACINGAPP"."HANDICAPCONTROL"
SELECT nextval('key'), current_timestamp, boat, handicap
FROM temp_dest;

ALTER TABLE "RACINGAPP"."SAILORUSER"
	ADD CONSTRAINT sailoruser_sailor_fk
	FOREIGN KEY (sailor)
	REFERENCES "RACINGAPP"."SAILORCONTROL"(key);

ALTER TABLE "RACINGAPP"."RACE"
	ALTER COLUMN key SET DEFAULT nextval('key');

ALTER TABLE "RACINGAPP"."CLUBUSER"
	ALTER COLUMN key SET DEFAULT nextval('key');

ALTER TABLE "RACINGAPP"."SAILORUSER"
	ALTER COLUMN key SET DEFAULT nextval('key');

ALTER TABLE "RACINGAPP"."RACE_ENTRY"
	ALTER COLUMN key SET DEFAULT nextval('key');

ALTER TABLE "RACINGAPP"."LAP"
	ALTER COLUMN key SET DEFAULT nextval('key');


ALTER TABLE "RACINGAPP"."CLUBCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."CLUBUSER"
	ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."SAILORUSER"
	ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

-- Series Control

-- ALTER TABLE "RACINGAPP"."SERIESCONTROL"
-- 	ALTER COLUMN year SET DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);

	
ALTER TABLE "RACINGAPP"."SERIESCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."SAILORCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "RACINGAPP"."BOATCONTROL"
  ALTER COLUMN "key" ADD GENERATED BY DEFAULT AS IDENTITY;




-- ALTER TABLE "RACINGAPP"."SERIESCONTROL"
--   ADD CONSTRAINT seriescontrol_year_name_uq UNIQUE (y



